name: personal-finance
version: '0.1.0.0'
synopsis: Some tools to manage my personal finance
category: Finance
author: Alexey Lebedeff
maintainer: binarin@binarin.ru
license: Apache-2.0
homepage: https://github.com/binarin/personal-finance
extra-source-files:
  - README.org
dependencies:
  - cryptonite
  - raw-strings-qq
  - sqlite-simple
  - cassava
  - aeson-pretty
  - terminal-size
  - base
  - monad-logger
  - prettyprinter
  - prettyprinter-ansi-terminal
  - threepenny-gui
  - process
  - extra
  - temporary
  - clay
  - text
  - time
  - containers
  - bytestring
  - mtl
  - exceptions
  - data-default
  - lens
  - managed
  - directory
  - aeson
  - scientific
  - wreq
  - lens-aeson
  - fast-logger
  - parsec
  - stm
default-extensions:
  - OverloadedStrings
  - BangPatterns
  - RankNTypes
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - LambdaCase
library:
  source-dirs: lib

executables:
  personal-finance:
    main: Main.hs
    dependencies:
      - personal-finance
    source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - hspec
      - personal-finance
