name: personal-finance
version: '0.1.0.0'
synopsis: Some tools to manage my personal finance
category: Finance
author: Alexey Lebedeff
maintainer: binarin@binarin.ru
license: Apache-2.0
homepage: https://github.com/binarin/personal-finance
extra-source-files:
  - README.org
dependencies:
  - base >=4.9 && <4.10
default-extensions:
  - OverloadedStrings
library:
  source-dirs: lib

executables:
  personal-finance:
    main: Main.hs
    dependencies:
      - personal-finance
    source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - hspec
      - personal-finance
